spring:
  datasource:
    url: jdbc:mariadb://exhibition2021.cxwkwp1k9z9o.ap-northeast-2.rds.amazonaws.com:3306/exhibition
    driver-class-name: org.mariadb.jdbc.Driver
    username: exhibition2021
    password: exhibition2021
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create